# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weed', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='plant-images')),
            ],
        ),
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
        migrations.DeleteModel(
            name='Plants',
        ),
    ]
