# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_userscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserScore',
            new_name='UserProfile',
        ),
    ]
